@startuml
title Activity Diagram 

start
:Користувач надсилає запит на перевірку чистоти повітря;
if (Успішно?) then (Так)
  :Співпрацівник офісу реагує на запит;
  :Передає інформацію співпрацівнику тех. відділу;
  if (Успішно?) then (Так)
    :Користувач отримує відповідь щодо чистоти повітря;
  else (Ні)
    :Помилка;
  endif
else (Ні)
  :Очікування відповіді;
endif
stop

@enduml